server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/BenjaminMoya/tingeso-ev2/CreditAdministrationApplication
          search-paths: config-data
