apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db
data:
  POSTGRES_DB_HOST: postgres
  POSTGRES_DB: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-costdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_COST: costdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-creditdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_CREDIT: creditdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-evaluationdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_EVALUATION: evaluationdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-filedb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_FILE: filedb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-simulationdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_SIMULATION: simulationdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-trackingdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_TRACKING: trackingdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-userdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_USER: userdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  script.sql: |
    CREATE DATABASE userdb;