apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db
data:
  POSTGRES_DB: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-costdb
data:
  host: postgres  
  name: costdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-creditdb
data:
  host: postgres  
  name: creditdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-evaluationdb
data:
  host: postgres  
  name: evaluationdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-filedb
data:
  host: postgres  
  name: filedb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-simulationdb
data:
  host: postgres  
  name: simulationdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-trackingdb
data:
  host: postgres  
  name: trackingdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-userdb
data:
  host: postgres  
  name: userdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: | 
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'costdb') THEN
        CREATE DATABASE costdb;
      END IF;
    END $$;
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'creditdb') THEN
        CREATE DATABASE creditdb;
      END IF;
    END $$;
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'evaluationdb') THEN
        CREATE DATABASE evaluationdb;
      END IF;
    END $$;
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'filedb') THEN
        CREATE DATABASE filedb;
      END IF;
    END $$;
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'simulationdb') THEN
        CREATE DATABASE simulationdb;
      END IF;
    END $$;
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'trackingdb') THEN
        CREATE DATABASE trackingdb;
      END IF;
    END $$;
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'userdb') THEN
        CREATE DATABASE userdb;
      END IF;
    END $$;

