apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: localhost
  POSTGRES_DB_COST: cost
  POSTGRES_DB_CREDIT: credit
  POSTGRES_DB_EVALUATION: evaluation
  POSTGRES_DB_FILE: file
  POSTGRES_DB_SIMULATION: simulation
  POSTGRES_DB_TRACKING: tracking
  POSTGRES_DB_USER: user