apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-deployment
  labels:
    app: simulation-deployment
spec:
  selector:
    matchLabels:
      app: simulation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: simulation-deployment
    spec:
      containers:
        - name: kubernetes-simulation
          image: benjaminmoya/kubernetes-simulation:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_SIMULATION
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_SIMULATION
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: simulation-service
  labels:
    app: simulation-service
spec:
  selector:
    app: simulation-deployment
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  type: LoadBalancer